#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

${PREFIX}pytest ${1-"./tests"}
${PREFIX}black {{cookiecutter.project_slug}} tests/ --check
${PREFIX}flake8 {{cookiecutter.project_slug}} tests/
