#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

export PYTHONPATH={{cookiecutter.project_slug}}
export SIMPLE_SETTINGS=settings

${PREFIX}pytest ${1-"./tests"} ${2}
${PREFIX}black {{cookiecutter.project_slug}} tests/ --check --diff
${PREFIX}flake8 {{cookiecutter.project_slug}} tests/
