#!/bin/sh -e

VERSION=`cat setup.py | grep '__version__ =' | sed 's/__version__ = //' | sed 's/"//g'`

# Creating git tag
echo "Considering doing the following actions:"
echo "git tag -a v${VERSION} -m 'release previous-version → v${VERSION}'"
echo "git push origin v${VERSION}"
