#!/bin/sh -e

set -o errexit
project_name="my_awesome_faust_project"

# install test requirements
pip install faust simple-settings
pip install -r ./requirements.txt

# create a cache directory
mkdir -p .cache/docker
cd .cache/docker

# create the project using the default settings in cookiecutter.json
cookiecutter ../../ --no-input --overwrite-if-exists $@
cd ${project_name}

docker-compose stop
echo yes | docker-compose rm

docker network rm ${project_name} || true

./scripts/test

# Listing the agents to prove that the project generated is working 
docker-compose run -e SIMPLE_SETTINGS=${project_name}.settings ${project_name} faust -A ${project_name}.app agents
