#!/bin/sh -e

TEST_FOLDER=.test-docker

set -o errexit
PROJECT_NAME="my_awesome_faust_project"

# create a cache directory
mkdir -p ${TEST_FOLDER}
cd ${TEST_FOLDER}

# create the project using the default settings in cookiecutter.json
cookiecutter ../ --no-input --overwrite-if-exists $@
cd ${PROJECT_NAME}

make stop-kafka-cluster

echo "running on ${ENVIRONMENT}"

# install test requirements and run test
if [ "$ENVIRONMENT" = "CI" ]
then
    pip install -r requirements/test.txt
else
    make install-test
fi

./scripts/test
docker-compose up -d

# Listing the agents to prove that the project generated is working
export KAFKA_BOOTSTRAP_SERVER_NAME=localhost
export KAFKA_BOOTSTRAP_SERVER_PORT=29092

./scripts/wait-for-services

if [ "$ENVIRONMENT" = "CI" ]
then
    export WORKER_PORT=6066
    export SIMPLE_SETTINGS=${PROJECT_NAME}.settings
    PYTHONPATH=${PROJECT_NAME} faust -A app agents
else
    make list-agents
fi

# Clean containers and code
make stop-kafka-cluster
